const ADD_SOURCE = 'ADD_SOURCE';
const ADD_MULTIPLE_SOURCES = 'DECREMADD_MULTIPLE_SOURCESENT_ACTIVE_STEP';
const REMOVE_SOURCE = 'REMOVE_SOURCE';

export default {
  ADD_SOURCE,
  ADD_MULTIPLE_SOURCES,
  REMOVE_SOURCE
};
