const TOGGLE_OPTION = 'TOGGLE_OPTION';
const ADD_FILTERS = 'ADD_FILTERS';
const ADD_FILTER = 'ADD_FILTER';
const TOGGLE_FILTER = 'TOGGLE_FILTER';
const TOGGLE_EXPAND_FILTER = 'TOGGLE_EXPAND_FILTER';
const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';

export default {
  TOGGLE_OPTION,
  ADD_FILTER,
  ADD_FILTERS,
  TOGGLE_FILTER,
  TOGGLE_EXPAND_FILTER,
  TOGGLE_CHECKBOX
};
