const SET_USER_PROFILE = 'SET_USER_PROFILE';
const ADD_DISCOVERY_SESSION = 'ADD_DISCOVERY_SESSION';
const ADD_EXECUTION_SESSION = 'ADD_EXECUTION_SESSION';
const UPDATE_EXECUTION_SESSION = 'UPDATE_EXECUTION_SESSION';
const UPDATE_DISCOVERY_SESSION = 'UPDATE_DISCOVERY_SESSION';
const UPDATE_APPLICATIONS_FOLDER = 'UPDATE_APPLICATIONS_FOLDER';

export default {
  SET_USER_PROFILE,
  ADD_DISCOVERY_SESSION,
  ADD_EXECUTION_SESSION,
  UPDATE_DISCOVERY_SESSION,
  UPDATE_EXECUTION_SESSION,
  UPDATE_APPLICATIONS_FOLDER
};
