const ADD_EXECUTION = 'ADD_EXECUTION';
const REMOVE_EXECUTION = 'REMOVE_EXECUTION';
const ADD_EXPORT = 'ADD_EXPORT';
const REMOVE_EXPORT = 'REMOVE_EXPORT';

export default {
  ADD_EXECUTION,
  REMOVE_EXECUTION,
  ADD_EXPORT,
  REMOVE_EXPORT
};
