const SET_SELECTED_VISUALIZER = 'SET_SELECTED_VISUALIZER';
const SET_CHOOSE_FOLDER_DIALOG_STATE = 'SET_CHOOSE_FOLDER_DIALOG_STATE';
const SET_LIGHT_COLOR_THEME = 'SET_LIGHT_COLOR_THEME';
const SET_INBOX_DIALOG_STATE = 'SET_INBOX_DIALOG_STATE';
const SET_ACCESS_CONTROL_DIALOG_STATE = 'SET_ACCESS_CONTROL_DIALOG_STATE';
const SET_SELECTED_DASHBOARD_TAB_INDEX = 'SET_SELECTED_DASHBOARD_TAB_INDEX';
const SET_MOBILE_DRAWER_STATE = 'SET_MOBILE_DRAWER_STATE';

export default {
  SET_SELECTED_VISUALIZER,
  SET_CHOOSE_FOLDER_DIALOG_STATE,
  SET_LIGHT_COLOR_THEME,
  SET_SELECTED_DASHBOARD_TAB_INDEX,
  SET_INBOX_DIALOG_STATE,
  SET_ACCESS_CONTROL_DIALOG_STATE,
  SET_MOBILE_DRAWER_STATE
};
