const SET_DISCOVERY_ID = 'SET_DISCOVERY_ID';
const SET_PIPELINE_ID = 'SET_PIPELINE_ID';
const SET_SELECTED_VISUALIZER = 'SET_SELECTED_VISUALIZER';
const SET_SELECTED_DATASOURCES_EXAMPLE = 'SET_SELECTED_DATASOURCES_EXAMPLE';
const SET_SELECTED_RESULT_GRAPH_IRI = 'SET_SELECTED_RESULT_GRAPH_IRI';
const TAB_CHANGED = 'TAB_CHANGED';

export default {
  SET_DISCOVERY_ID,
  SET_PIPELINE_ID,
  SET_SELECTED_VISUALIZER,
  SET_SELECTED_DATASOURCES_EXAMPLE,
  SET_SELECTED_RESULT_GRAPH_IRI,
  TAB_CHANGED
};
