const SET_SELECTED_VISUALIZER = 'SET_SELECTED_VISUALIZER';
const SET_CHOOSE_FOLDER_DIALOG_STATE = 'SET_CHOOSE_FOLDER_DIALOG_STATE';
const SET_LIGHT_COLOR_THEME = 'SET_LIGHT_COLOR_THEME';

export default {
  SET_SELECTED_VISUALIZER,
  SET_CHOOSE_FOLDER_DIALOG_STATE,
  SET_LIGHT_COLOR_THEME
};
