javadoc:
  sourceDirs:
  - '../../../../src/main/java'
  classPages:
    menu:
    - type: 'javadocClassLinks'
  pages:
    menu:
    - type: 'javadocPackages'

site:
  about:
    siteName: 'LPA Backend Documentation'

theme:
  social:
    github: 'linkedpipes/applications'
  menu:
  - type: 'link'
    title: 'Home'
    url: '/'
  - type: 'link'
    title: 'Javadoc'
    url: '/com/linkedpipes/lpa/backend'
  extraCss:
  - 'assets/css/sideNav.css'
  - 'assets/css/color.css'
