javadoc:
  sourceDirs:
  - '../../../../src/main/java'
  classPages:
    menu:
    - type: 'javadocClassLinks'
  pages:
    menu:
    - type: 'javadocPackages'

site:
  about:
    siteName: 'LPA Backend Documentation'

theme:
  social:
    github: 'linkedpipes/applications'
  menu:
  - type: 'link'
    title: 'Home'
    url: '/'
  - type: 'link'
    title: 'Javadoc'
    url: '/com/linkedpipes/lpa/backend'
  #    - type: 'pages'
  #      atRoot: true
  extraCss:
  - 'assets/css/sideNav.css'
  extraJs:
  - 'assets/js/extraJs.js'

services:
  generators:
    externalIndices:
    - 'https://orchid.netlify.com/meta/all.index.json'
