# build environment
FROM node:8.15.0-alpine as builder

# Install packages using Yarn
# References:
# http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/
# https://hackernoon.com/using-yarn-with-docker-c116ad289d56

# Add package.json and respective lock
ADD package.json yarn.* /tmp/

# Install git 
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

# Install packages
RUN cd /tmp && yarn install --frozen-lockfile --check-files

# Create a symlink to node_modules
RUN mkdir -p /usr/src/app && cd /usr/src/app && ln -s /tmp/node_modules

WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY . /usr/src/app
RUN yarn build


# Production environment image
FROM nginx:alpine
COPY --from=builder /usr/src/app/public /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 
