const INCREMENT_ACTIVE_STEP = 'INCREMENT_ACTIVE_STEP';
const DECREMENT_ACTIVE_STEP = 'DECREMENT_ACTIVE_STEP';
const RESET_ACTIVE_STEP = 'RESET_ACTIVE_STEP';
const SET_SELECTED_INPUT_EXAMPLE = 'SET_SELECTED_INPUT_EXAMPLE';
const SET_ETL_EXECUTION_STATUS = 'SET_ETL_EXECUTION_STATUS';
const TAB_CHANGED = 'TAB_CHANGED';
const RESET_SELECTED_INPUT_EXAMPLE = 'RESET_SELECTED_INPUT_EXAMPLE';

export default {
  INCREMENT_ACTIVE_STEP,
  DECREMENT_ACTIVE_STEP,
  RESET_ACTIVE_STEP,
  SET_SELECTED_INPUT_EXAMPLE,
  RESET_SELECTED_INPUT_EXAMPLE,
  SET_ETL_EXECUTION_STATUS,
  TAB_CHANGED
};
