const INCREMENT_ACTIVE_STEP = 'INCREMENT_ACTIVE_STEP';
const DECREMENT_ACTIVE_STEP = 'DECREMENT_ACTIVE_STEP';
const RESET_ACTIVE_STEP = 'RESET_ACTIVE_STEP';
const SET_SELECTED_INPUT_EXAMPLE = 'SET_SELECTED_INPUT_EXAMPLE';
const CHANGE_TAB = 'CHANGE_TAB';
const SET_ETL_EXECUTION_STATUS = 'SET_ETL_EXECUTION_STATUS';

export default {
  INCREMENT_ACTIVE_STEP,
  DECREMENT_ACTIVE_STEP,
  RESET_ACTIVE_STEP,
  SET_SELECTED_INPUT_EXAMPLE,
  SET_ETL_EXECUTION_STATUS
  CHANGE_TAB
};
