const SET_APPLICATION = 'SET_APPLICATION';
const RESET_APPLICATION = 'SET_APPLICATION';
const SET_APPLICATION_TITLE = 'SET_APPLICATION_TITLE';
const RESET_APPLICATION_TITLE = 'RESET_APPLICATION_TITLE';

export default {
  SET_APPLICATION,
  RESET_APPLICATION,
  SET_APPLICATION_TITLE,
  RESET_APPLICATION_TITLE
};
